// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {agents} from '../models';

export function AddMCPServer(arg1:string,arg2:string):Promise<string>;

export function AskAgent(arg1:string,arg2:string):Promise<string>;

export function CheckConnection():Promise<boolean>;

export function ConsolidateChatKnowledge(arg1:string):Promise<string>;

export function FixEnvironment():Promise<string>;

export function GenerateGeminiMD():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetToolsStatus():Promise<Record<string, boolean>>;

export function InstallTool(arg1:string):Promise<string>;

export function ListAgentSessions(arg1:string):Promise<Array<agents.SessionInfo>>;

export function ListMCPServers():Promise<string>;

export function LoadAgentSession(arg1:string,arg2:string):Promise<void>;

export function NewAgentSession(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanVault():Promise<string>;

export function SendAgentInput(arg1:string,arg2:string,arg3:Array<Record<string, string>>):Promise<void>;

export function SendTerminalData(arg1:string,arg2:string):Promise<string>;

export function SetAutonomousMode(arg1:boolean):Promise<string>;

export function SetupTool(arg1:string):Promise<string>;

export function StartAgentSession(arg1:string):Promise<void>;

export function StartLoginSession(arg1:string):Promise<string>;

export function StopAgentSession(arg1:string):Promise<void>;

export function SubmitReview(arg1:string,arg2:boolean):Promise<void>;
