// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AskAgent(arg1, arg2) {
  return window['go']['main']['App']['AskAgent'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function FixEnvironment() {
  return window['go']['main']['App']['FixEnvironment']();
}

export function GenerateGeminiMD() {
  return window['go']['main']['App']['GenerateGeminiMD']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ListAgentSessions(arg1) {
  return window['go']['main']['App']['ListAgentSessions'](arg1);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function LoadAgentSession(arg1, arg2) {
  return window['go']['main']['App']['LoadAgentSession'](arg1, arg2);
}

export function NewAgentSession(arg1) {
  return window['go']['main']['App']['NewAgentSession'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanVault() {
  return window['go']['main']['App']['ScanVault']();
}

export function SendAgentInput(arg1, arg2) {
  return window['go']['main']['App']['SendAgentInput'](arg1, arg2);
}

export function SendTerminalData(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalData'](arg1, arg2);
}

export function SetAutonomousMode(arg1) {
  return window['go']['main']['App']['SetAutonomousMode'](arg1);
}

export function SetupTool(arg1) {
  return window['go']['main']['App']['SetupTool'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StartLoginSession(arg1) {
  return window['go']['main']['App']['StartLoginSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function SubmitReview(arg1, arg2) {
  return window['go']['main']['App']['SubmitReview'](arg1, arg2);
}
